# Generated by Django 3.2 on 2021-04-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pv',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='uv',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
