# Generated by Django 3.2 on 2021-04-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210420_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pv',
        ),
        migrations.RemoveField(
            model_name='category',
            name='uv',
        ),
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='uv',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
